packages:
  - apps/*

# แพ็กเกจที่อนุญาตให้รัน build script ตอนติดตั้ง
allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1140.0'
  - '@aws-sdk/s3-request-presigner@3.1140.0'
